### ISSUE TITLE
Can this be updated to 0.16.0.2?

### ISSUE THREAD

**Issue by jeffwong-nflx** [conda-forge/r-arrow-feedstock#18]
Hi, I would love to have this updated to match CRAN's arrow 0.16.0.2, found here
https://cran.r-project.org/src/contrib/Archive/arrow/

AFAIK, conda-forge has a bot that synchronizes CRAN updates with conda-forge feedstocks. Did that get activated for 0.16.0.2?

**Comment by dpryan79** [comment]
There's a PR to update this to 0.17, but that will need arrow-cpp to be updated and it's having compilation issues at the moment: https://github.com/conda-forge/arrow-cpp-feedstock/pull/132

**Comment by xhochy** [comment]
I'm taking care of https://github.com/conda-forge/arrow-cpp-feedstock/pull/132, will probably land this afternoon.

**Comment by xhochy** [comment]
0.17 was merged. Please make a manual PR if you really want 0.16.0.2
